// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BBBB_MXRENDER_DATA_H_
#define FLATBUFFERS_GENERATED_BBBB_MXRENDER_DATA_H_

#include "flatbuffers/flatbuffers.h"

namespace MXRender {
namespace Data {

struct Vec3;

struct Monster2;
struct Monster2Builder;
struct Monster2T;

struct Weapon2;
struct Weapon2Builder;
struct Weapon2T;

bool operator==(const Vec3 &lhs, const Vec3 &rhs);
bool operator!=(const Vec3 &lhs, const Vec3 &rhs);
bool operator==(const Monster2T &lhs, const Monster2T &rhs);
bool operator!=(const Monster2T &lhs, const Monster2T &rhs);
bool operator==(const Weapon2T &lhs, const Weapon2T &rhs);
bool operator!=(const Weapon2T &lhs, const Weapon2T &rhs);

inline const flatbuffers::TypeTable *Vec3TypeTable();

inline const flatbuffers::TypeTable *Monster2TypeTable();

inline const flatbuffers::TypeTable *Weapon2TypeTable();

enum Color2 {
  Color2_Red = 0,
  Color2_Green = 1,
  Color2_Blue = 2,
  Color2_MIN = Color2_Red,
  Color2_MAX = Color2_Blue
};

inline const Color2 (&EnumValuesColor2())[3] {
  static const Color2 values[] = {
    Color2_Red,
    Color2_Green,
    Color2_Blue
  };
  return values;
}

inline const char * const *EnumNamesColor2() {
  static const char * const names[4] = {
    "Red",
    "Green",
    "Blue",
    nullptr
  };
  return names;
}

inline const char *EnumNameColor2(Color2 e) {
  if (flatbuffers::IsOutRange(e, Color2_Red, Color2_Blue)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColor2()[index];
}

enum Equipment2 {
  Equipment2_NONE = 0,
  Equipment2_Weapon2 = 1,
  Equipment2_MIN = Equipment2_NONE,
  Equipment2_MAX = Equipment2_Weapon2
};

inline const Equipment2 (&EnumValuesEquipment2())[2] {
  static const Equipment2 values[] = {
    Equipment2_NONE,
    Equipment2_Weapon2
  };
  return values;
}

inline const char * const *EnumNamesEquipment2() {
  static const char * const names[3] = {
    "NONE",
    "Weapon2",
    nullptr
  };
  return names;
}

inline const char *EnumNameEquipment2(Equipment2 e) {
  if (flatbuffers::IsOutRange(e, Equipment2_NONE, Equipment2_Weapon2)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEquipment2()[index];
}

template<typename T> struct Equipment2Traits {
  static const Equipment2 enum_value = Equipment2_NONE;
};

template<> struct Equipment2Traits<MXRender::Data::Weapon2> {
  static const Equipment2 enum_value = Equipment2_Weapon2;
};

struct Equipment2Union {
  Equipment2 type;
  void *value;

  Equipment2Union() : type(Equipment2_NONE), value(nullptr) {}
  Equipment2Union(Equipment2Union&& u) FLATBUFFERS_NOEXCEPT :
    type(Equipment2_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  Equipment2Union(const Equipment2Union &);
  Equipment2Union &operator=(const Equipment2Union &u)
    { Equipment2Union t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  Equipment2Union &operator=(Equipment2Union &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~Equipment2Union() { Reset(); }

  void Reset();

#ifndef FLATBUFFERS_CPP98_STL
  template <typename T>
  void Set(T&& val) {
    using RT = typename std::remove_reference<T>::type;
    Reset();
    type = Equipment2Traits<typename RT::TableType>::enum_value;
    if (type != Equipment2_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }
#endif  // FLATBUFFERS_CPP98_STL

  static void *UnPack(const void *obj, Equipment2 type, const flatbuffers::resolver_function_t *resolver);
  flatbuffers::Offset<void> Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  MXRender::Data::Weapon2T *AsWeapon2() {
    return type == Equipment2_Weapon2 ?
      reinterpret_cast<MXRender::Data::Weapon2T *>(value) : nullptr;
  }
  const MXRender::Data::Weapon2T *AsWeapon2() const {
    return type == Equipment2_Weapon2 ?
      reinterpret_cast<const MXRender::Data::Weapon2T *>(value) : nullptr;
  }
};


inline bool operator==(const Equipment2Union &lhs, const Equipment2Union &rhs) {
  if (lhs.type != rhs.type) return false;
  switch (lhs.type) {
    case Equipment2_NONE: {
      return true;
    }
    case Equipment2_Weapon2: {
      return *(reinterpret_cast<const MXRender::Data::Weapon2T *>(lhs.value)) ==
             *(reinterpret_cast<const MXRender::Data::Weapon2T *>(rhs.value));
    }
    default: {
      return false;
    }
  }
}

inline bool operator!=(const Equipment2Union &lhs, const Equipment2Union &rhs) {
    return !(lhs == rhs);
}

bool VerifyEquipment2(flatbuffers::Verifier &verifier, const void *obj, Equipment2 type);
bool VerifyEquipment2Vector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Vec3TypeTable();
  }
  Vec3() {
    memset(static_cast<void *>(this), 0, sizeof(Vec3));
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

inline bool operator==(const Vec3 &lhs, const Vec3 &rhs) {
  return
      (lhs.x() == rhs.x()) &&
      (lhs.y() == rhs.y()) &&
      (lhs.z() == rhs.z());
}

inline bool operator!=(const Vec3 &lhs, const Vec3 &rhs) {
    return !(lhs == rhs);
}


struct Monster2T : public flatbuffers::NativeTable {
  typedef Monster2 TableType;
  std::unique_ptr<MXRender::Data::Vec3> pos;
  int16_t mana;
  int16_t hp;
  std::string name;
  std::vector<uint8_t> inventory;
  MXRender::Data::Color2 color;
  std::vector<std::unique_ptr<MXRender::Data::Weapon2T>> weapons;
  MXRender::Data::Equipment2Union equipped;
  std::vector<MXRender::Data::Vec3> path;
  Monster2T()
      : mana(150),
        hp(100),
        color(MXRender::Data::Color2_Blue) {
  }
};

inline bool operator==(const Monster2T &lhs, const Monster2T &rhs) {
  return
      (lhs.pos == rhs.pos) &&
      (lhs.mana == rhs.mana) &&
      (lhs.hp == rhs.hp) &&
      (lhs.name == rhs.name) &&
      (lhs.inventory == rhs.inventory) &&
      (lhs.color == rhs.color) &&
      (lhs.weapons == rhs.weapons) &&
      (lhs.equipped == rhs.equipped) &&
      (lhs.path == rhs.path);
}

inline bool operator!=(const Monster2T &lhs, const Monster2T &rhs) {
    return !(lhs == rhs);
}


struct Monster2 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Monster2T NativeTableType;
  typedef Monster2Builder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Monster2TypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4,
    VT_MANA = 6,
    VT_HP = 8,
    VT_NAME = 10,
    VT_INVENTORY = 14,
    VT_COLOR = 16,
    VT_WEAPONS = 18,
    VT_EQUIPPED_TYPE = 20,
    VT_EQUIPPED = 22,
    VT_PATH = 24
  };
  const MXRender::Data::Vec3 *pos() const {
    return GetStruct<const MXRender::Data::Vec3 *>(VT_POS);
  }
  int16_t mana() const {
    return GetField<int16_t>(VT_MANA, 150);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 100);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<uint8_t> *inventory() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_INVENTORY);
  }
  MXRender::Data::Color2 color() const {
    return static_cast<MXRender::Data::Color2>(GetField<int8_t>(VT_COLOR, 2));
  }
  const flatbuffers::Vector<flatbuffers::Offset<MXRender::Data::Weapon2>> *weapons() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<MXRender::Data::Weapon2>> *>(VT_WEAPONS);
  }
  MXRender::Data::Equipment2 equipped_type() const {
    return static_cast<MXRender::Data::Equipment2>(GetField<uint8_t>(VT_EQUIPPED_TYPE, 0));
  }
  const void *equipped() const {
    return GetPointer<const void *>(VT_EQUIPPED);
  }
  template<typename T> const T *equipped_as() const;
  const MXRender::Data::Weapon2 *equipped_as_Weapon2() const {
    return equipped_type() == MXRender::Data::Equipment2_Weapon2 ? static_cast<const MXRender::Data::Weapon2 *>(equipped()) : nullptr;
  }
  const flatbuffers::Vector<const MXRender::Data::Vec3 *> *path() const {
    return GetPointer<const flatbuffers::Vector<const MXRender::Data::Vec3 *> *>(VT_PATH);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<MXRender::Data::Vec3>(verifier, VT_POS) &&
           VerifyField<int16_t>(verifier, VT_MANA) &&
           VerifyField<int16_t>(verifier, VT_HP) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_INVENTORY) &&
           verifier.VerifyVector(inventory()) &&
           VerifyField<int8_t>(verifier, VT_COLOR) &&
           VerifyOffset(verifier, VT_WEAPONS) &&
           verifier.VerifyVector(weapons()) &&
           verifier.VerifyVectorOfTables(weapons()) &&
           VerifyField<uint8_t>(verifier, VT_EQUIPPED_TYPE) &&
           VerifyOffset(verifier, VT_EQUIPPED) &&
           VerifyEquipment2(verifier, equipped(), equipped_type()) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyVector(path()) &&
           verifier.EndTable();
  }
  Monster2T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Monster2T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Monster2> Pack(flatbuffers::FlatBufferBuilder &_fbb, const Monster2T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const MXRender::Data::Weapon2 *Monster2::equipped_as<MXRender::Data::Weapon2>() const {
  return equipped_as_Weapon2();
}

struct Monster2Builder {
  typedef Monster2 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pos(const MXRender::Data::Vec3 *pos) {
    fbb_.AddStruct(Monster2::VT_POS, pos);
  }
  void add_mana(int16_t mana) {
    fbb_.AddElement<int16_t>(Monster2::VT_MANA, mana, 150);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(Monster2::VT_HP, hp, 100);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Monster2::VT_NAME, name);
  }
  void add_inventory(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> inventory) {
    fbb_.AddOffset(Monster2::VT_INVENTORY, inventory);
  }
  void add_color(MXRender::Data::Color2 color) {
    fbb_.AddElement<int8_t>(Monster2::VT_COLOR, static_cast<int8_t>(color), 2);
  }
  void add_weapons(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<MXRender::Data::Weapon2>>> weapons) {
    fbb_.AddOffset(Monster2::VT_WEAPONS, weapons);
  }
  void add_equipped_type(MXRender::Data::Equipment2 equipped_type) {
    fbb_.AddElement<uint8_t>(Monster2::VT_EQUIPPED_TYPE, static_cast<uint8_t>(equipped_type), 0);
  }
  void add_equipped(flatbuffers::Offset<void> equipped) {
    fbb_.AddOffset(Monster2::VT_EQUIPPED, equipped);
  }
  void add_path(flatbuffers::Offset<flatbuffers::Vector<const MXRender::Data::Vec3 *>> path) {
    fbb_.AddOffset(Monster2::VT_PATH, path);
  }
  explicit Monster2Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  Monster2Builder &operator=(const Monster2Builder &);
  flatbuffers::Offset<Monster2> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Monster2>(end);
    return o;
  }
};

inline flatbuffers::Offset<Monster2> CreateMonster2(
    flatbuffers::FlatBufferBuilder &_fbb,
    const MXRender::Data::Vec3 *pos = 0,
    int16_t mana = 150,
    int16_t hp = 100,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> inventory = 0,
    MXRender::Data::Color2 color = MXRender::Data::Color2_Blue,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<MXRender::Data::Weapon2>>> weapons = 0,
    MXRender::Data::Equipment2 equipped_type = MXRender::Data::Equipment2_NONE,
    flatbuffers::Offset<void> equipped = 0,
    flatbuffers::Offset<flatbuffers::Vector<const MXRender::Data::Vec3 *>> path = 0) {
  Monster2Builder builder_(_fbb);
  builder_.add_path(path);
  builder_.add_equipped(equipped);
  builder_.add_weapons(weapons);
  builder_.add_inventory(inventory);
  builder_.add_name(name);
  builder_.add_pos(pos);
  builder_.add_hp(hp);
  builder_.add_mana(mana);
  builder_.add_equipped_type(equipped_type);
  builder_.add_color(color);
  return builder_.Finish();
}

inline flatbuffers::Offset<Monster2> CreateMonster2Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const MXRender::Data::Vec3 *pos = 0,
    int16_t mana = 150,
    int16_t hp = 100,
    const char *name = nullptr,
    const std::vector<uint8_t> *inventory = nullptr,
    MXRender::Data::Color2 color = MXRender::Data::Color2_Blue,
    const std::vector<flatbuffers::Offset<MXRender::Data::Weapon2>> *weapons = nullptr,
    MXRender::Data::Equipment2 equipped_type = MXRender::Data::Equipment2_NONE,
    flatbuffers::Offset<void> equipped = 0,
    const std::vector<MXRender::Data::Vec3> *path = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto inventory__ = inventory ? _fbb.CreateVector<uint8_t>(*inventory) : 0;
  auto weapons__ = weapons ? _fbb.CreateVector<flatbuffers::Offset<MXRender::Data::Weapon2>>(*weapons) : 0;
  auto path__ = path ? _fbb.CreateVectorOfStructs<MXRender::Data::Vec3>(*path) : 0;
  return MXRender::Data::CreateMonster2(
      _fbb,
      pos,
      mana,
      hp,
      name__,
      inventory__,
      color,
      weapons__,
      equipped_type,
      equipped,
      path__);
}

flatbuffers::Offset<Monster2> CreateMonster2(flatbuffers::FlatBufferBuilder &_fbb, const Monster2T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Weapon2T : public flatbuffers::NativeTable {
  typedef Weapon2 TableType;
  std::string name;
  int16_t damage;
  Weapon2T()
      : damage(0) {
  }
};

inline bool operator==(const Weapon2T &lhs, const Weapon2T &rhs) {
  return
      (lhs.name == rhs.name) &&
      (lhs.damage == rhs.damage);
}

inline bool operator!=(const Weapon2T &lhs, const Weapon2T &rhs) {
    return !(lhs == rhs);
}


struct Weapon2 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Weapon2T NativeTableType;
  typedef Weapon2Builder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return Weapon2TypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DAMAGE = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  int16_t damage() const {
    return GetField<int16_t>(VT_DAMAGE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int16_t>(verifier, VT_DAMAGE) &&
           verifier.EndTable();
  }
  Weapon2T *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Weapon2T *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Weapon2> Pack(flatbuffers::FlatBufferBuilder &_fbb, const Weapon2T* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Weapon2Builder {
  typedef Weapon2 Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Weapon2::VT_NAME, name);
  }
  void add_damage(int16_t damage) {
    fbb_.AddElement<int16_t>(Weapon2::VT_DAMAGE, damage, 0);
  }
  explicit Weapon2Builder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  Weapon2Builder &operator=(const Weapon2Builder &);
  flatbuffers::Offset<Weapon2> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Weapon2>(end);
    return o;
  }
};

inline flatbuffers::Offset<Weapon2> CreateWeapon2(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    int16_t damage = 0) {
  Weapon2Builder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_damage(damage);
  return builder_.Finish();
}

inline flatbuffers::Offset<Weapon2> CreateWeapon2Direct(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int16_t damage = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return MXRender::Data::CreateWeapon2(
      _fbb,
      name__,
      damage);
}

flatbuffers::Offset<Weapon2> CreateWeapon2(flatbuffers::FlatBufferBuilder &_fbb, const Weapon2T *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Monster2T *Monster2::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<MXRender::Data::Monster2T> _o = std::unique_ptr<MXRender::Data::Monster2T>(new Monster2T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Monster2::UnPackTo(Monster2T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = pos(); if (_e) _o->pos = std::unique_ptr<MXRender::Data::Vec3>(new MXRender::Data::Vec3(*_e)); }
  { auto _e = mana(); _o->mana = _e; }
  { auto _e = hp(); _o->hp = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = inventory(); if (_e) { _o->inventory.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->inventory[_i] = _e->Get(_i); } } }
  { auto _e = color(); _o->color = _e; }
  { auto _e = weapons(); if (_e) { _o->weapons.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->weapons[_i] = std::unique_ptr<MXRender::Data::Weapon2T>(_e->Get(_i)->UnPack(_resolver)); } } }
  { auto _e = equipped_type(); _o->equipped.type = _e; }
  { auto _e = equipped(); if (_e) _o->equipped.value = MXRender::Data::Equipment2Union::UnPack(_e, equipped_type(), _resolver); }
  { auto _e = path(); if (_e) { _o->path.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->path[_i] = *_e->Get(_i); } } }
}

inline flatbuffers::Offset<Monster2> Monster2::Pack(flatbuffers::FlatBufferBuilder &_fbb, const Monster2T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMonster2(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Monster2> CreateMonster2(flatbuffers::FlatBufferBuilder &_fbb, const Monster2T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const Monster2T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _pos = _o->pos ? _o->pos.get() : 0;
  auto _mana = _o->mana;
  auto _hp = _o->hp;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _inventory = _o->inventory.size() ? _fbb.CreateVector(_o->inventory) : 0;
  auto _color = _o->color;
  auto _weapons = _o->weapons.size() ? _fbb.CreateVector<flatbuffers::Offset<MXRender::Data::Weapon2>> (_o->weapons.size(), [](size_t i, _VectorArgs *__va) { return CreateWeapon2(*__va->__fbb, __va->__o->weapons[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _equipped_type = _o->equipped.type;
  auto _equipped = _o->equipped.Pack(_fbb);
  auto _path = _o->path.size() ? _fbb.CreateVectorOfStructs(_o->path) : 0;
  return MXRender::Data::CreateMonster2(
      _fbb,
      _pos,
      _mana,
      _hp,
      _name,
      _inventory,
      _color,
      _weapons,
      _equipped_type,
      _equipped,
      _path);
}

inline Weapon2T *Weapon2::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<MXRender::Data::Weapon2T> _o = std::unique_ptr<MXRender::Data::Weapon2T>(new Weapon2T());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Weapon2::UnPackTo(Weapon2T *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = damage(); _o->damage = _e; }
}

inline flatbuffers::Offset<Weapon2> Weapon2::Pack(flatbuffers::FlatBufferBuilder &_fbb, const Weapon2T* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateWeapon2(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Weapon2> CreateWeapon2(flatbuffers::FlatBufferBuilder &_fbb, const Weapon2T *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const Weapon2T* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _damage = _o->damage;
  return MXRender::Data::CreateWeapon2(
      _fbb,
      _name,
      _damage);
}

inline bool VerifyEquipment2(flatbuffers::Verifier &verifier, const void *obj, Equipment2 type) {
  switch (type) {
    case Equipment2_NONE: {
      return true;
    }
    case Equipment2_Weapon2: {
      auto ptr = reinterpret_cast<const MXRender::Data::Weapon2 *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyEquipment2Vector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEquipment2(
        verifier,  values->Get(i), types->GetEnum<Equipment2>(i))) {
      return false;
    }
  }
  return true;
}

inline void *Equipment2Union::UnPack(const void *obj, Equipment2 type, const flatbuffers::resolver_function_t *resolver) {
  switch (type) {
    case Equipment2_Weapon2: {
      auto ptr = reinterpret_cast<const MXRender::Data::Weapon2 *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline flatbuffers::Offset<void> Equipment2Union::Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher) const {
  switch (type) {
    case Equipment2_Weapon2: {
      auto ptr = reinterpret_cast<const MXRender::Data::Weapon2T *>(value);
      return CreateWeapon2(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline Equipment2Union::Equipment2Union(const Equipment2Union &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Equipment2_Weapon2: {
      value = new MXRender::Data::Weapon2T(*reinterpret_cast<MXRender::Data::Weapon2T *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void Equipment2Union::Reset() {
  switch (type) {
    case Equipment2_Weapon2: {
      auto ptr = reinterpret_cast<MXRender::Data::Weapon2T *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Equipment2_NONE;
}

inline const flatbuffers::TypeTable *Color2TypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_CHAR, 0, 0 },
    { flatbuffers::ET_CHAR, 0, 0 },
    { flatbuffers::ET_CHAR, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    MXRender::Data::Color2TypeTable
  };
  static const char * const names[] = {
    "Red",
    "Green",
    "Blue"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *Equipment2TypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, -1 },
    { flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    MXRender::Data::Weapon2TypeTable
  };
  static const char * const names[] = {
    "NONE",
    "Weapon2"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_UNION, 2, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *Vec3TypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8, 12 };
  static const char * const names[] = {
    "x",
    "y",
    "z"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 3, type_codes, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *Monster2TypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SHORT, 0, -1 },
    { flatbuffers::ET_SHORT, 0, -1 },
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_BOOL, 0, -1 },
    { flatbuffers::ET_UCHAR, 1, -1 },
    { flatbuffers::ET_CHAR, 0, 1 },
    { flatbuffers::ET_SEQUENCE, 1, 2 },
    { flatbuffers::ET_UTYPE, 0, 3 },
    { flatbuffers::ET_SEQUENCE, 0, 3 },
    { flatbuffers::ET_SEQUENCE, 1, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    MXRender::Data::Vec3TypeTable,
    MXRender::Data::Color2TypeTable,
    MXRender::Data::Weapon2TypeTable,
    MXRender::Data::Equipment2TypeTable
  };
  static const char * const names[] = {
    "pos",
    "mana",
    "hp",
    "name",
    "friendly",
    "inventory",
    "color",
    "weapons",
    "equipped_type",
    "equipped",
    "path"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 11, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *Weapon2TypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_SHORT, 0, -1 }
  };
  static const char * const names[] = {
    "name",
    "damage"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, names
  };
  return &tt;
}

inline const MXRender::Data::Monster2 *GetMonster2(const void *buf) {
  return flatbuffers::GetRoot<MXRender::Data::Monster2>(buf);
}

inline const MXRender::Data::Monster2 *GetSizePrefixedMonster2(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<MXRender::Data::Monster2>(buf);
}

inline bool VerifyMonster2Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MXRender::Data::Monster2>(nullptr);
}

inline bool VerifySizePrefixedMonster2Buffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MXRender::Data::Monster2>(nullptr);
}

inline const char *Monster2Extension() {
  return "bfbs";
}

inline void FinishMonster2Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MXRender::Data::Monster2> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMonster2Buffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MXRender::Data::Monster2> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<MXRender::Data::Monster2T> UnPackMonster2(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MXRender::Data::Monster2T>(GetMonster2(buf)->UnPack(res));
}

inline std::unique_ptr<MXRender::Data::Monster2T> UnPackSizePrefixedMonster2(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MXRender::Data::Monster2T>(GetSizePrefixedMonster2(buf)->UnPack(res));
}

}  // namespace Data
}  // namespace MXRender

#endif  // FLATBUFFERS_GENERATED_BBBB_MXRENDER_DATA_H_
