#pragma once
// Auto-generated by MetaParser. Do not edit.
// RmlUI DataModel bindings generated from META annotations.

#include <RmlUi/Core/DataModelHandle.h>

namespace MXRender {
namespace UI {
namespace RmlUI {
namespace Generated {

inline void BindRmlUIDemoApp(Rml::DataModelConstructor& ctor, RmlUIDemoApp* data)
{
	ctor.Bind("hp", &data->m_hp);
	ctor.Bind("score", &data->m_score);
	ctor.Bind("timer", &data->m_timer);

}

} // namespace Generated
} // namespace RmlUI
} // namespace UI
} // namespace MXRender

