#pragma once
// Auto-generated by MetaParser. Do not edit.
// UIWidget BindingTraits for classes with UI_BIND_* annotations.

#include <RmlUi/Core/DataModelHandle.h>
#include "UI/Widget/UIWidgetBinding.h"
#include "..\..\Sample\12-RmlUI\RmlUIDemo.h"

namespace MXRender {
namespace UI {
namespace Widget {

template<>
struct UIWidgetBindingTraits<RmlUIDemoApp>
{
	static void BindDataModel(void* ctor_opaque, RmlUIDemoApp* data)
	{
		auto& ctor = *static_cast<Rml::DataModelConstructor*>(ctor_opaque);
		ctor.Bind("hp", &data->m_hp);
		ctor.Bind("score", &data->m_score);
		ctor.Bind("timer", &data->m_timer);
		ctor.Bind("m_player_name", &data->m_player_name);
		ctor.Bind("m_volume", &data->m_volume);
		ctor.BindEventCallback("on_heal",
			[data](Rml::DataModelHandle handle, Rml::Event& event, const Rml::VariantList& /*arguments*/) {
				data->OnHeal(handle, event);
			});
	}

	static Vector<UIBindingEntry> GetBindingEntries(const rttr::type& type)
	{
		return {
			{ "hp", type.get_property("m_hp"), EBindingMode::OneWay, {} },
			{ "score", type.get_property("m_score"), EBindingMode::OneWay, {} },
			{ "timer", type.get_property("m_timer"), EBindingMode::OneWay, {} },
			{ "m_player_name", type.get_property("m_player_name"), EBindingMode::OneWay, {} },
			{ "m_volume", type.get_property("m_volume"), EBindingMode::TwoWay, {} },
		};
	}

	static Map<String, Map<String, String>> GetFieldMetadata()
	{
		return {};
	}
};

} // namespace Widget
} // namespace UI
} // namespace MXRender

