toolchain("myclang")
    set_kind("standalone")
    set_toolset("cc", "clang")
    set_toolset("cxx", "clang", "clang++")
    set_toolset("ld", "clang++", "clang")
    set_toolset("sh", "clang++", "clang")
    set_toolset("ar", "ar")
    set_toolset("ex", "ar")
    set_toolset("strip", "strip")
    set_toolset("mm", "clang")
    set_toolset("mxx", "clang", "clang++")
    set_toolset("as", "clang")

target("MetaParser")
    set_kind("binary")  
    set_languages("c++20")  
    set_group("Reflect")
    set_toolchains("myclang")
    add_files("parser/main.cpp")

    add_includedirs("3rd_party/LLVM/include")
    add_includedirs("3rd_party/mustache")
    add_includedirs("parser")
    add_headerfiles("3rd_party/**.hpp")
    add_headerfiles("3rd_party/**.h")
    add_headerfiles("parser/**.hpp")
    add_headerfiles("parser/**.h")
    add_files("parser/**.cpp")     
    add_linkdirs("$(projectdir)/src/Reflect/meta_parser/3rd_party/LLVM/lib/x64")
    add_links("$(projectdir)/src/Reflect/meta_parser/3rd_party/LLVM/lib/x64/libclang.lib")