#pragma once
#ifndef _MESHLOADER_
#define _MESHLOADER_
#include "Core/ConstDefine.h"

MYRENDERER_BEGIN_NAMESPACE(MXRender)
MYRENDERER_BEGIN_NAMESPACE(Tool)

MYRENDERER_END_NAMESPACE
MYRENDERER_END_NAMESPACE
#endif