#version 460
layout(local_size_x=256)in;
layout(set=0,binding=0)buffer p0_Buf{float d[];}p0;
layout(set=0,binding=1)readonly buffer g0_Buf{float d[];}g0;
layout(set=0,binding=2)buffer v0_Buf{float d[];}v0;
layout(set=0,binding=10)readonly buffer pcc_Buf{float d[];}pcc;
void main(){uint g=gl_GlobalInvocationID.x;if(g>=uint(pcc.d[4]))return;
float r=g0.d[g]*pcc.d[3]+pcc.d[2]*p0.d[g];
float v=pcc.d[1]*v0.d[g]+r;v0.d[g]=v;p0.d[g]-=pcc.d[0]*v;}
