// Sample: HelloTriangleAndroid
// Minimal Vulkan triangle on Android — no RenderGraph, no Window, no file I/O.
// SPIR-V embedded via GenCode headers. Single-threaded.
//
// Entry point: android_main() (called by android_native_app_glue)

#if PLATFORM_ANDROID

#include "Application/Android/AndroidApp.h"
#include "RHI/RenderRHI.h"
#include "RHI/RenderRource.h"
#include "RHI/RenderPipelineState.h"
#include "RHI/ResourceManager.h"
#include "RHI/RenderCommandList.h"
#include "RHI/RenderTexture.h"
#include "RHI/RenderViewport.h"
#include "Core/ConstDefine.h"

// Embedded SPIR-V (generated by glsl2spv build rule)
static const UInt32 kTriangleVertSpv[] = {
#include "GenCode/Shader/triangle_test.vert.spv.h"
};
static const UInt32 kTriangleFragSpv[] = {
#include "GenCode/Shader/triangle_test.frag.spv.h"
};

using namespace MXRender;
using namespace MXRender::RHI;
using namespace MXRender::Application;

struct SampleState
{
	PSOHandle pipeline;
	ShaderResourceBinding* srb = nullptr;
	Viewport* viewport = nullptr;

	void Release()
	{
		if (srb) { delete srb; srb = nullptr; }
		// pipeline owned by VK_PipelineStateManager
	}
};

static void OnInit(SampleState& state, AndroidApp& app)
{
	state.viewport = app.GetViewport();

	// Create shaders from embedded SPIR-V
	ShaderDesc vs_desc;
	vs_desc.shader_type = ENUM_SHADER_STAGE::Shader_Vertex;
	vs_desc.shader_name = "triangle_test.vert";
	vs_desc.entry_name = "main";
	ShaderDataPayload vs_payload;
	vs_payload.data = reinterpret_cast<const char*>(kTriangleVertSpv);
	vs_payload.size = sizeof(kTriangleVertSpv);
	Shader* vs = RHICreateShader(vs_desc, vs_payload);

	ShaderDesc ps_desc;
	ps_desc.shader_type = ENUM_SHADER_STAGE::Shader_Pixel;
	ps_desc.shader_name = "triangle_test.frag";
	ps_desc.entry_name = "main";
	ShaderDataPayload ps_payload;
	ps_payload.data = reinterpret_cast<const char*>(kTriangleFragSpv);
	ps_payload.size = sizeof(kTriangleFragSpv);
	Shader* ps = RHICreateShader(ps_desc, ps_payload);

	// Create pipeline state
	RenderGraphiPipelineStateDesc pso_desc;
	pso_desc.shaders[ENUM_SHADER_STAGE::Shader_Vertex] = vs;
	pso_desc.shaders[ENUM_SHADER_STAGE::Shader_Pixel] = ps;
	pso_desc.primitive_topology = ENUM_PRIMITIVE_TYPE::TriangleList;
	pso_desc.render_targets = { state.viewport->GetCurrentBackBufferRTV() };
	pso_desc.depth_stencil_view = state.viewport->GetCurrentBackBufferDSV();
	pso_desc.raster_state.sample_count = 1;
	pso_desc.blend_state.render_targets.resize(1);

	state.pipeline = g_render_rhi->CreateRenderPipelineState(pso_desc);
	state.pipeline->CreateShaderResourceBinding(state.srb);

	delete vs;
	delete ps;
}

static void OnFrame(SampleState& state)
{
	if (!state.pipeline || !state.srb || !state.viewport)
		return;

	CommandList* cmd = RHIGetImmediateCommandList();
	if (!cmd) return;

	Texture* rtv = state.viewport->GetCurrentBackBufferRTV();
	Texture* dsv = state.viewport->GetCurrentBackBufferDSV();

	Vector<Texture*> rtvs = { rtv };
	Vector<ClearValue> clears;
	clears.push_back(rtv->GetTextureDesc().clear_value);
	if (dsv)
		clears.push_back(dsv->GetTextureDesc().clear_value);

	cmd->Begin();
	cmd->SetRenderTarget(rtvs, dsv, clears, dsv != nullptr);
	cmd->SetGraphicsPipeline(state.pipeline);
	cmd->SetShaderResourceBinding(state.srb);

	DrawAttribute draw_attr;
	draw_attr.vertexCount = 3;
	draw_attr.instanceCount = 1;
	cmd->Draw(draw_attr);

	cmd->End();
	state.viewport->Present(cmd, true, true);
}

// Android native entry point — the OS calls this function.
extern "C" void android_main(struct android_app* app_state)
{
	AndroidApp app(app_state);
	SampleState sample;

	app.Run(
		[&] { OnInit(sample, app); },
		[&] { OnFrame(sample); },
		[&] { sample.Release(); }
	);
}

#endif // PLATFORM_ANDROID
